customCommands:
  images:
    - name: "Run Container (Keep Alive)"
      attach: false
      command: "docker run -d -it {{ .Image.Name }} sh"
    - name: "Run Container (Detach)"
      attach: false
      command: "docker run -d {{ .Image.Name }}"
