gui:
  returnImmediately: true
customCommands:
  images:
    - name: "Run Container (Keep Alive)"
      attach: false
      command: 'docker run --network host --name "{{ .Image.Name }}" -d -it {{ .Image.Name }} sh'
    - name: "Run Container (Detach)"
      attach: false
      command: 'docker run --network host --name "{{ .Image.Name }}" -d {{ .Image.Name }}'
