# General settings
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# Set C-a to be the prefix instead of C-b
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Set zsh as default shell
set-option -g default-shell /usr/bin/zsh

# Open panes in current directory
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

# yank
set -g @yank_action 'copy-pipe'

# catppuccin
set -g @plugin 'catppuccin/tmux#v2.3.0' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
# --- Active Window (Looks Regular) ---
# set -g @catppuccin_window_current_background "#{@thm_surface_1}"
# set -g @catppuccin_window_current_text_color "#{@thm_fg}"
#
# # --- Inactive Windows (Muted & Darker) ---
# # Uses 'mantle' for a darker background and 'overlay_0' to dim the text
# set -g @catppuccin_window_default_background "#{@thm_mantle}"
# set -g @catppuccin_window_default_text_color "#{@thm_overlay_0}"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# ressurect
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim "session"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

